---
version: 2
models:
- name: "customers"
  description: "This pipeline graph provides a comprehensive report on customer behavior,\
    \ including order history, payment patterns, and customer lifetime value (CLV).\
    \ By combining data from multiple sources, including orders, payments, and customer\
    \ information, businesses can gain a holistic view of customer behavior and make\
    \ data-driven decisions related to customer retention, targeted marketing strategies,\
    \ and overall business growth. The report includes customer details such as name,\
    \ first and most recent order dates, total number of orders, and customer lifetime\
    \ value, and can be sorted by any of these metrics to provide insights into customer\
    \ behavior and performance."
  columns:
  - name: "customer_id"
    description: "This is a unique identifier for a customer"
    tests:
    - "unique"
    - "not_null"
  - name: "first_name"
    description: "Customer's first name. PII."
  - name: "last_name"
    description: "Customer's last name. PII."
  - name: "first_order"
    description: "Date (UTC) of a customer's first order"
  - name: "most_recent_order"
    description: "Date (UTC) of a customer's most recent order"
  - name: "number_of_orders"
    description: "Count of the number of orders a customer has placed"
  - name: "total_order_amount"
    description: "Total value (AUD) of a customer's orders"
- name: "orders"
  description: "This table has basic information about orders, as well as some derived\
    \ facts based on payments"
  columns:
  - name: "order_id"
    description: "This is a unique identifier for an order"
    tests:
    - "unique"
    - "not_null"
  - name: "customer_id"
    description: "Foreign key to the customers table"
    tests:
    - "not_null"
    - relationships:
        to: "ref('customers')"
        field: "customer_id"
  - name: "order_date"
    description: "Date (UTC) that the order was placed"
  - name: "status"
    description: "{{ doc(\"orders_status\") }}"
    tests:
    - accepted_values:
        values:
        - "placed"
        - "shipped"
        - "completed"
        - "return_pending"
        - "returned"
  - name: "amount"
    description: "Total amount (AUD) of the order"
    tests:
    - "not_null"
  - name: "credit_card_amount"
    description: "Amount of the order (AUD) paid for by credit card"
    tests:
    - "not_null"
  - name: "coupon_amount"
    description: "Amount of the order (AUD) paid for by coupon"
    tests:
    - "not_null"
  - name: "bank_transfer_amount"
    description: "Amount of the order (AUD) paid for by bank transfer"
    tests:
    - "not_null"
  - name: "gift_card_amount"
    description: "Amount of the order (AUD) paid for by gift card"
    tests:
    - "not_null"
